### ISSUE TITLE
Workflow BDTopo - List

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#246]
List all the issues related to the BD Topo workflow

- [x] #233 Workflow fails when creating `zone_neighbors`
- [x] #243 `ZONE` is empty (so also the other tables)
- [x] #244  Water fraction (bug with 56007, 56167, 56184)
- [x] #247 Vegetation fraction (bug with 56087)
- [x] #250 Wrong SRID on output results
- [x] #251 Remove buildings / blocks that do not belong to the zone
- [x] #252 `Hole lies outside shell at or near point` on building (74010)
- [x] #253 Blocks are multipolygon due to point intersection between buildings
- [x] #254 Do not try to save the RsuLCZ (output from Geoindicators workflow)
- [x] #260 Improve the final log message 
- [x] #304 Problem with .SHP extension (lower / upper case)
- [x] #306 Workflow BD Topo - no EPSG code in outputs
- [x] #310 Not possible to execute multiple id_zones in the same time
- [x] #322 Pblm from DB to DB
- [x] #363 DB to DB - missing objects
- [x] #364 DB to DB - specify a schema
- [x] #394 DB to DB - can not add new zone
- [ ] #398 DB to DB - Wrong results when adding a new zone

@ebocher @j3r3m1 @SPalominos

**Comment by ebocher** [comment]
To be updated
