### ISSUE TITLE
WorkFlow OSM - List

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#262]
List of issues to solve for OSM:

- [x] #261:
- [x] #263: manage the place names having "-" or white space.
- [x] #264: make valid the RSU geometries
- [x] #265: trouble with accents and getSpatialTable
